### ISSUE TITLE
not working give working example please

### ISSUE THREAD

**Issue by bitcoin5000** [sberbank-ai/ru-clip#12]
please give working Jupyter notebook example or python code , not working
i use example and it not working, have rtx 3090
error:

`NameError                                 Traceback (most recent call last)
<ipython-input-9-175737caa68e> in <module>
     20 
     21 # show results
---> 22 f, ax = plt.subplots(2,4, figsize=(12,6))
     23 for i, (pil_img, pred_label) in enumerate(zip(images, pred_labels)):
     24     ax[i//4, i%4].imshow(pil_img)

NameError: name 'plt' is not defined
`

**Comment by shonenkov** [comment]
https://github.com/sberbank-ai/ru-clip/commit/1695f998599e28d966249100dc639854eb2109aa
